version: "3.0"
services:
  chocon:
    container_name: chocon
    build:
      context: ../.
      dockerfile: ./benchmark/chocon/Dockerfile
    cap_add:
      - NET_ADMIN    
  server:
    container_name: server
    build: ./server
    cap_add:
      - NET_ADMIN
  client:
    container_name: client
    build: ./client
    tty: true
    cap_add:
      - NET_ADMIN
