name: test
on:
  push:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: test
        run: |
          make check
          make linux-check

      - name: Snapshot GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: build --snapshot